### PR TITLE
Allow Ruby 3.0

### PR DESCRIPTION
**Pull request by dgodd**
- Relax required_ruby_version to allow 3.0.0
- Test newer ruby versions on travis

### CODE REVIEW

**Comment by jlebray** [comment]
Hi, any reasons not to merge this ?

**Comment by brianbrazil** [comment]
@sj26 Can this be merged

**Comment by sj26** [comment]
Yes, thanks!

**Comment by sj26** [comment]
Released in [v2.1.0](https://github.com/sj26/sidekiq-cloudwatchmetrics/releases/tag/v2.1.0)

**Pull request merged**
