### PR TITLE
Allow process dimensions (tag and hostname) to be disabled

### PR DESCRIPTION
**Pull request by kylerippey**
This is something we've found helpful here at Recurrent. Since we run our Sidekiq workers in serverless containers with dynamic and randomly generated internal hostnames, tracking the hostname dimension created a lot of unnecessary extra Cloudwatch metrics. This is a patch that we added that allows us to disable that dimension like so:

```ruby
Sidekiq::CloudWatchMetrics.enable!(namespace: "Sidekiq/#{Rails.env}", process_dimensions: {hostname: false})
```

We've been running this patch in production for almost a year with no issues.

If there's a different way you'd like to implement this, just let me know and I would be happy to make adjustments. I'm also open to ideas on the best way to write tests for this. I was looking at adding another context block to `"#publish"`, but it would require a bit of refactoring of the shared examples to get them to work in all scenarios.

Thanks for your consideration!

### CODE REVIEW

**Comment by kei500** [comment]
@sj26 How about this patch?
We also want to use this option in the same use case.

**Comment by sj26** [comment]
Interesting. Do you want to exclude per-process metrics entirely? Are you only using the consolidated "Utilization" metric for scaling?

**Comment by sj26** [comment]
Would this do what you want?

https://github.com/sj26/sidekiq-cloudwatchmetrics/compare/per-process-metrics

**Comment by kylerippey** [comment]
> Interesting. Do you want to exclude per-process metrics entirely? Are you only using the consolidated "Utilization" metric for scaling? Why do you want to remove the metrics — are they causing expense, or just noise?

That's correct, we're really only using the consolidated utilization metric for scaling purposes. I think your `process_metrics: false` solution will work for our needs. We'll give it a try soon. Thanks!

**Comment by kei500** [comment]
@sj26 

> are they causing expense, or just noise?

Both of them.

> Would this do what you want?

Thanks, it looks good. Please release a new version.

**Comment by matt-domsch-sp** [comment]
I have a similar need - needing only Utilization (as input to autoscaling) and EnqueuedJobs (for visualization of overall backlog). Today we made a private fork and stripped everything out but these two metrics, as it added hundreds of dollars a month to publish all the stats that we didn't otherwise need.

**Comment by matt-domsch-sp** [comment]
As another aside, we also either lower the loglevel of  or omit logging messages all together on every publish. This winds being tens of thousands a day in our environments. Correct operation is silent operation.

**Comment by kylerippey** [comment]
Closing this in favor of @sj26's suggestion. Thanks!

**Pull request closed without merging**
