### PR TITLE
Allow namespace to be configured (e.g. "Sidekiq-Staging", "Sidekiq-Prod")

### LINKED ISSUE #7: Custom Namespaces
Love the gem, we are using it for autoscaling worker instances based on queue depth.

One challenge that we have encountered is this doesn't really play well with multiple environments, or multiple different types of worker instance since metrics are published to the same namespace.

I'd love a way to customize this on initialization, so for example:

```ruby
Sidekiq::CloudWatchMetrics.enable!(client: ..., namespace: "Sidekiq-Staging")
```

### PR DESCRIPTION
**Pull request by ndbroadbent**
Fixes #7

### CODE REVIEW

**Comment by davidguthu** [comment]
@sj26 any reason we can't get this pulled into master ?

**Comment by sj26** [comment]
Thanks, this is great!

**Comment by sj26** [comment]
I'd encourage you to look closely at how AWS chooses namespaces and dimensions though, and use `additional_dimensions: {"Environment" => "Staging"}` etc

**Comment by sj26** [comment]
Released in [v2.1.0](https://github.com/sj26/sidekiq-cloudwatchmetrics/releases/tag/v2.1.0)

**Pull request merged**
